
--[[------------------------------------------------------------------------------
-- <auto-generated>
--     This code was generated by a tool.
--     Changes to this file may cause incorrect behavior and will be lost if
--     the code is regenerated.
-- </auto-generated>
--]]------------------------------------------------------------------------------


local enums =
{
}

local beans = {}
    do
    ---@class player.player 
     ---@field public level integer @等级
     ---@field public exp integer @经验
        local class = {
            { name='level', type='integer'},
            { name='exp', type='integer'},
        }
        beans['player.player'] = class
    end

local tables =
{
    { name='level', file='player_level', mode='map', index='level', value_type='player.player' },
}

return { enums = enums, beans = beans, tables = tables }

