
--[[------------------------------------------------------------------------------
-- <auto-generated>
--     This code was generated by a tool.
--     Changes to this file may cause incorrect behavior and will be lost if
--     the code is regenerated.
-- </auto-generated>
--]]------------------------------------------------------------------------------


local enums =
{
    ---@class email_type @邮件类型
     ---@field public GLOBAL integer @全服邮件
     ---@field public SYSTEM integer @系统邮件
     ---@field public FRIEND integer @好友邮件
    ['email_type'] = {   GLOBAL=1,  SYSTEM=2,  FRIEND=3,  };
    ---@class friend_email_id @好友邮件ID
     ---@field public GOLD_REWARD integer @好友金币赠送
    ['friend_email_id'] = {   GOLD_REWARD=0,  };
    ---@class game_type @游戏类型
     ---@field public CHINESE_CHESS integer @中国象棋游戏
     ---@field public DIGITALBOMB integer @数字炸弹游戏
    ['game_type'] = {   CHINESE_CHESS=1,  DIGITALBOMB=2,  };
    ---@class item_ID @道具ID
     ---@field public PROP_SILVER integer @普通货币
     ---@field public PROP_GOLD integer @高级货币
     ---@field public PROP_EXP integer @玩家经验值
    ['item_ID'] = {   PROP_SILVER=10000001,  PROP_GOLD=10000002,  PROP_EXP=10000003,  };
    ---@class item_main_type @道具类型
     ---@field public PROP integer @没有特殊类型的道具
    ['item_main_type'] = {   PROP=1,  };
    ---@class item_sub_type @道具子类型
    ['item_sub_type'] = {   };
    ---@class play_type @玩法类型
     ---@field public CC_RANKING integer @排位赛玩法
     ---@field public CC_FIVE_MINUTE integer @5分钟场
     ---@field public CC_TEN_MINUTE integer @10分钟场
     ---@field public DB_RANGE_100 integer @范围100玩法
     ---@field public DB_RANGE_10000 integer @范围10000玩法
    ['play_type'] = {   CC_RANKING=10001,  CC_FIVE_MINUTE=10002,  CC_TEN_MINUTE=10003,  DB_RANGE_100=20001,  DB_RANGE_10000=20002,  };
    ---@class sys_email_id @系统邮件ID
     ---@field public LOGIN_REWARD integer @每日登录奖励
    ['sys_email_id'] = {   LOGIN_REWARD=0,  };
}

local beans = {}
    do
    ---@class chess.chess_param 
     ---@field public init_score integer @初始分数
     ---@field public low_level_cond integer @低等级条件
     ---@field public win_add_score integer @赢加分
     ---@field public lose_reduce_score integer @输减分
     ---@field public low_win_add_score integer @低等级赢加分
     ---@field public low_lose_reduce_score integer @低等级输减分
        local class = {
            { name='init_score', type='integer'},
            { name='low_level_cond', type='integer'},
            { name='win_add_score', type='integer'},
            { name='lose_reduce_score', type='integer'},
            { name='low_win_add_score', type='integer'},
            { name='low_lose_reduce_score', type='integer'},
        }
        beans['chess.chess_param'] = class
    end
    do
    ---@class chess.chess_rank 
     ---@field public rank_id integer @段位ID
     ---@field public level integer @段位等级
     ---@field public rank_name string @段位名称
     ---@field public need_score integer @目标分数
        local class = {
            { name='rank_id', type='integer'},
            { name='level', type='integer'},
            { name='rank_name', type='string'},
            { name='need_score', type='integer'},
        }
        beans['chess.chess_rank'] = class
    end
    do
    ---@class chess.chess_type 
     ---@field public play_type integer @玩法类型
     ---@field public total_time integer @总局时(秒)
     ---@field public doing_time integer @操作时长(秒)
     ---@field public win_rewards table<integer,integer> @获胜奖励
     ---@field public fail_rewards table<integer,integer> @失败奖励
        local class = {
            { name='play_type', type='integer'},
            { name='total_time', type='integer'},
            { name='doing_time', type='integer'},
            { name='win_rewards', type='table<integer,integer>'},
            { name='fail_rewards', type='table<integer,integer>'},
        }
        beans['chess.chess_type'] = class
    end
    do
    ---@class email.email_friend 
     ---@field public id integer @好友邮件ID
     ---@field public title string @邮件标题
     ---@field public content string @邮件内容
     ---@field public vaild_time integer @有效时间(秒)(0表示永久)
        local class = {
            { name='id', type='integer'},
            { name='title', type='string'},
            { name='content', type='string'},
            { name='vaild_time', type='integer'},
        }
        beans['email.email_friend'] = class
    end
    do
    ---@class email.email_sys 
     ---@field public id integer @系统邮件ID
     ---@field public title string @邮件标题
     ---@field public content string @邮件内容
     ---@field public vaild_time integer @有效时间(秒)(0表示永久)
        local class = {
            { name='id', type='integer'},
            { name='title', type='string'},
            { name='content', type='string'},
            { name='vaild_time', type='integer'},
        }
        beans['email.email_sys'] = class
    end
    do
    ---@class item.item_info 
     ---@field public item_id integer @道具ID
     ---@field public main_type integer @道具类型
     ---@field public sub_type integer @子类型
     ---@field public item_name string @道具名称
        local class = {
            { name='item_id', type='integer'},
            { name='main_type', type='integer'},
            { name='sub_type', type='integer'},
            { name='item_name', type='string'},
        }
        beans['item.item_info'] = class
    end
    do
    ---@class match.match_game 
     ---@field public game_type integer @游戏类型
     ---@field public play_type integer @玩法类型
        local class = {
            { name='game_type', type='integer'},
            { name='play_type', type='integer'},
        }
        beans['match.match_game'] = class
    end
    do
    ---@class misc.misc_param 
     ---@field public login_rewards table<integer,integer> @每日登录奖励
        local class = {
            { name='login_rewards', type='table<integer,integer>'},
        }
        beans['misc.misc_param'] = class
    end
    do
    ---@class player.player_level 
     ---@field public level integer @等级
     ---@field public exp integer @经验
        local class = {
            { name='level', type='integer'},
            { name='exp', type='integer'},
        }
        beans['player.player_level'] = class
    end

local tables =
{
    { name='tb_player_level', file='player_level', mode='map', index='level', value_type='player.player_level' },
    { name='tb_item_info', file='item_info', mode='map', index='item_id', value_type='item.item_info' },
    { name='tb_chess_type', file='chess_type', mode='map', index='play_type', value_type='chess.chess_type' },
    { name='tb_chess_param', file='chess_param', mode='one', value_type='chess.chess_param'},
    { name='tb_chess_rank', file='chess_rank', mode='map', index='rank_id', value_type='chess.chess_rank' },
    { name='tb_match_game', file='match_game', mode='list', index='', value_type='match.match_game' },
    { name='tb_email_sys', file='email_sys', mode='map', index='id', value_type='email.email_sys' },
    { name='tb_email_friend', file='email_friend', mode='list', index='', value_type='email.email_friend' },
    { name='tb_misc_param', file='misc_param', mode='one', value_type='misc.misc_param'},
}

return { enums = enums, beans = beans, tables = tables }

